genesis_id = ""
system = "Viberate"
dependencies = ["Ethereum"]
icon = "viberate"

[token]
name = "Viberate"
symbol = "VIB"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Decentralized music talent marketplace "

[crowdsales]
start_date = "2017-09-05T08:00:00"
end_date = "2017-10-04T08:00:00"
end_date_plan = "2017-10-04T08:00:00"
genesis_address = [""]
funding_terms = "https://www.viberate.io/en/crowdsale"
funding_url = "https://www.viberate.io/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "viberate.io"
url = "https://www.viberate.io"
tags = ["Main"]

[[links]]
type = "paper"
name = "Viberate Whitepaper"
url = "https://www.viberate.io/Viberate_ICO_Whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "blog"
name = "Viberate Blog"
url = "https://medium.com/viberate-blog"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/viberate_com"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2029450.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Viberate Telegram"
url = "https://t.me/ViberateOfficial"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/viberateOFC/"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCNqR72YOybyCZzVhb5oeQhw"
icon = "youtube.png"
tags = ["News"]
